on:
  push:
    branches: main
    paths-ignore:
      - "docs/**"
  pull_request:
    types: [opened, synchronize, reopened]
    branches: main

name: ğŸ¤– GDExtension

jobs:
  build:
    name: ğŸ—ï¸ Build / ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: ğŸ§ Linux (64-bit)
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os-name: ğŸ macOS (Universal)
            runs-on: macos-latest
            target: universal-apple-darwin
          - os-name: ğŸªŸ Windows (64-bit)
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: ${{ matrix.platform.runs-on == 'ubuntu-latest' }}
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libsoup-3.0-dev libwebkit2gtk-4.1-dev build-essential curl wget file libssl-dev libayatana-appindicator3-dev librsvg2-dev libjavascriptcoregtk-4.1-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target == 'universal-apple-darwin' && 'aarch64-apple-darwin,x86_64-apple-darwin' || matrix.platform.target }}

      - name: Install Just
        uses: extractions/setup-just@v1

      - name: Build binaries
        run: just ${{ matrix.platform.target == 'universal-apple-darwin' && 'build-macos-universal' || 'build' }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.target }}
          path: |
            rust/target/${{ matrix.platform.target }}/release/*.dll
            rust/target/${{ matrix.platform.target }}/release/*.so
            rust/target/${{ matrix.platform.target }}/release/*.dylib
            rust/target/${{ matrix.platform.target }}/release/*.framework

  zip:
    name: ğŸ“¦ Package
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          path: godot/addons/godot_wry/bin

      - name: Clean files
        run: |
          mkdir -p package/godot_wry
          mv godot/addons package/godot_wry

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot_wry
          path: package

  #TODO: release:
